### ISSUE TITLE
Typings errors in V. 3.0.0-alpha.5

### ISSUE THREAD

**Issue by saudraisn** [ctrlplusb/easy-peasy#242]
Hi, I had the **Type instantiation is excessively deep and possibly infinite** error  (issue #227) and I tried to fix it by upgrading to V. 3.0.0-alpha.5. (In a CRA project)

Typescript version : 3.5.1
Easy peasy version : 3.0.0-alpha.5

I now have the 2 following errors flagged in the **index.d.ts** file :

![image](https://user-images.githubusercontent.com/6865470/60732756-df8b7180-9f18-11e9-8b03-47e6070b3359.png)

Thanks for this awesome project!

**Comment by ctrlplusb** [comment]
Hey @saudraisn 

Glad you are liking it.

Is there any chance you could give me an example of your model, or better yet a reproducible example on codesandbox. That would save me lots of time, thanks.

**Comment by saudraisn** [comment]
I am working right now on a reproductible project, i will get back to you ASAP!

**Comment by saudraisn** [comment]
While reproducing the problem, i noticed that I have a type error in my migration from V2 to V3. I am using easy-peasy in parallel with react redux, so i have this code : 

![image](https://user-images.githubusercontent.com/6865470/60736428-eddf8a80-9f24-11e9-8874-87fc5a9247f0.png)

and this sample flags me the **Type 'Dispatch' is not generic.** error.

The **State<IApplicationModel>** is working, so was the Dispatch<IApplicationModel> before, but no longer in V3.

How could i get the right typed "dispatch" parameter on which i could have ts autocompletion without type errors to dispatch my actions correctly in the **mapDispatchToProps**?

Thanks for your help.

**Comment by ctrlplusb** [comment]
Woops, I messed up and removed the actions from `dispatch`. It completely makes sense to keep them bound to `dispatch` too in order to support `react-redux` projects. I will revert this change and do another release. 

So glad I am doing alpha releases now. Great opportunity to catch these mistakes before getting locked out of making breaking changes. :D

**Comment by ctrlplusb** [comment]
Hi @saudraisn - I have reverted this. The `Dispatch` should now work as expected. I am going to mark this issues with the docs label too so I remember to add a note about this within react-redux interop section.

**Comment by saudraisn** [comment]
Cool, glad I could help you find these!

Thanks for the very fast update!

**Comment by ctrlplusb** [comment]
Awesome, no problem, is your typescript working now?

**Comment by saudraisn** [comment]
I installed **easy-peasy@3.0.0-alpha.8** this morning and strangely, the errors are still there (the one in the **index.d.ts** file, the generic Dispatch is now working though!). 

I'll keep looking and keep you posted if i find something. I tried it in a new CRA app and everything seems to be fine.

**Comment by ctrlplusb** [comment]
Hey @saudraisn - the errors are surfacing from the underlying helper library I am using - `ts-toolbelt`. The authors are addressing it but in the interim those facing this may have to set the `skipLibCheck` setting to `true` on your `tsconfig.json`. I think the recent version of CRA does this by default.

**Comment by saudraisn** [comment]
Amazing, I tried it and everything is working that way! Thanks a lot for your quick support!

And yes, the latest CRA sets the _skipLibCheck_ to true by default.

**Comment by ctrlplusb** [comment]
I just published `easy-peasy@3.0.0-alpha.9` which fixes the issue - so you no longer have to set the `skipLibCheck` flag :D
